Fix bug that prevented linux standalone bundle from working on a fresh install
Bug was introduced in version 8.20201007, lost a necessary mkdir.

This commit was sponsored by Noam Kremen on Patreon.

diff --git a/standalone/linux/skel/runshell b/standalone/linux/skel/runshell
--- a/standalone/linux/skel/runshell
+++ b/standalone/linux/skel/runshell
@@ -151,6 +151,10 @@ if [ -z "${LOCPATH+set}" ] && [ -z "$GIT_ANNEX_PACKAGE_INSTALL" ]; then
 	done
 	
 	if [ ! -d "$LOCPATH" ]; then
+		if ! mkdir -p "$HOME/.cache/git-annex/locales"; then
+			echo "Unable to write to $HOME/.cache/git-annex/locales; can't continue!" >&2
+			exit 1
+		fi
 		locpathtmp="$HOME/.cache/git-annex/locales.tmp/$locpathbase.$$"
 		if ! mkdir -p "$locpathtmp"; then
 			echo "Unable to write to $locpathtmp; can't continue!" >&2
