add INPUT-REQUIRED
Used by git-annex-compute-singularity to make addcomputed --fast work.

Also, simplified git-annex-compute-singularity; there is no need to hard
link the container into place. singularity does not care about the
extension of the container, so can just pass it the annex object file.

diff --git a/doc/special_remotes/compute/git-annex-compute-singularity b/doc/special_remotes/compute/git-annex-compute-singularity
--- a/doc/special_remotes/compute/git-annex-compute-singularity
+++ b/doc/special_remotes/compute/git-annex-compute-singularity
@@ -78,17 +78,13 @@ else
 	echo "SANDBOX"
 	read pathtotop
 	binddir="$(realpath "$pathtotop")"
-	echo "INPUT $pathtotop/$ANNEX_COMPUTE_passthrough"
-	read input
-	if [ -n "$input" ]; then
-		container="./$ANNEX_COMPUTE_passthrough"
-		mkdir -p "$(dirname "$container")"
-		ln "$(realpath "$input")" "$container"
-	else
-		echo "Unfortunately, addcomputed --fast cannot be used with git-annex-compute-singularity --passthrough=" >&2
+	echo "INPUT-REQUIRED $pathtotop/$ANNEX_COMPUTE_passthrough"
+	read container
+	if [ -z "$container" ]; then
+		echo "Cannot proceed without container $ANNEX_COMPUTE_passthrough" >&2
 		exit 1
 	fi
 	# stdio is passed through to the git-annex-compute- command inside
-	# singularity
+	# the container
 	run_singularity "$@" 2> >( strip_escape 1>&2 )
 fi
