ENH: test for some expected build flags to be enabled across all platforms
Re Windows and Servant -- not sure yet it should be
asked: https://git-annex.branchable.com/forum/is_it_safe_to_enable_Servant_by_default__63__/#comment-c919d40111013cb3a6c2dcf76f12a09e

diff --git a/.github/workflows/build-windows.yaml b/.github/workflows/build-windows.yaml
--- a/.github/workflows/build-windows.yaml
+++ b/.github/workflows/build-windows.yaml
@@ -247,9 +247,15 @@ jobs:
           ls "$GIT_ANNEX_DIR"/*magic* "$GIT_ANNEX_DIR"/*gnurx*
           ls "$GIT_ANNEX_DIR"/../share/misc/*magic*
 
-      - name: Check git-annex version for MagicMime flag
+
+      - name: Check git-annex version for some expected build flags
         run: |
-          git annex version | grep 'build flags:.*MagicMime'
+          # apparently order is not alphabetic, so cannot be relied upon for a single grep
+          flags=$(git annex version | grep 'build flags:')
+          for f in Assistant MagicMime Servant S3; do
+            echo -n "Checking for $f: "
+            echo "$flags" | grep --color "$f" || { echo "FAIL"; exit 1; }
+          done
 
       - name: Print git-annex version
         run: git annex version
